### ISSUE TITLE
join JuliaStats ?

### ISSUE THREAD

**Issue by bjarthur** [juliangehring/Bootstrap.jl#4]
thanks for this!  looks great.

any reason not to place this package in the JuliaStats group?  would be easier to find.

**Comment by julian-gehring** [comment]
Thank you for the nice feedback. I'd love to have it in JuliaStats, but I haven't gotten yet in touch with the core team to get their opinion. Do you have direct contact to members of JuliaStats or are involved in the project?

At the moment, the package is still in a limbo state between the old stable version, and the refractored version with many more features. Due to time constraints on my side, I also doubt that I can bring the package into a stable, well documented version with the new features and API very soon. I'm not sure which level of maturity a packages needs to be interesting for JuliaStats - do you have any insights?

**Comment by bjarthur** [comment]
submit an issue there and ask to be included.  all code is a work in progress.  i find what you have so far very useful and would encourage them to add it to their umbrella.  just keep the unstable stuff in a separate branch, or if it's already in master don't tag a new version until it's stable.

**Comment by nignatiadis** [comment]
Though I think they are reluctant to accept new packages nowadays, see https://github.com/JuliaStats/Roadmap.jl/issues/19.

**Comment by bjarthur** [comment]
@simonster

**Comment by bjarthur** [comment]
well, i still think it's worth asking.

alternatively, you could try to merge your stuff into an existing repo.  when i first went searching for resampling methods, i went directly to [HypothesisTests.jl](https://github.com/JuliaStats/HypothesisTests.jl) and was surprised not to find it already there.

**Comment by juliangehring** [comment]
Wow, this has been open for a long time now. Time to have some closure.
I'll leave the package live here and don't plan to move it JuliaStats. `Bootstrap` is now part of [StatsKit](https://github.com/JuliaStats/StatsKit.jl) and easy to discover. Additionally, the main motivation to moving packages to JuliaStats seem to be (1) many contributors and (2) unmaintained packages (as [discussed](https://discourse.julialang.org/t/when-should-a-package-be-added-to-juliastats/10380/2) regarding a related package); both reasons don't seem to apply here. If this situation changes in the future, I'm happy to revisit this again.
