### ISSUE TITLE
Feature to retrieve all sampled results so that a histogram can be obtained

### ISSUE THREAD

**Issue by Boxylmer** [juliangehring/Bootstrap.jl#86]
Please forgive me if this feature exists, but is there a way to easily pull a list of the resampled outputs so that I can create a histogram of the values predicted? I'd like to get a convincing visual figure that shows I've used enough samples.

**Comment by juliangehring** [comment]
Are you looking for a way to collect 1) the resampled input `data` or 2) the outputs of the `statistic` function that was applied to the resampled data?

**Comment by Boxylmer** [comment]
The latter. If I hand Bootstrap an input of something like [1.2, 3.2, 1.1, 1.0, 0.9], and I get back a bunch of resampled values from the model being bootstrapped (say n=4) as [2.1, 2.2, 2.1, 2.0], I want that vector of outputs so that I can verify a histogram of the results "looks" correct. Is this already possible with the current exported functions?

**Comment by juliangehring** [comment]
Yes, you can get the output statistic of each resampling with the `straps` method (it should probably have a more meaningful name):

```julia
bs = bootstrap(median, [1.2, 3.2, 1.1, 1.0, 0.9], BasicSampling(5));
straps(bs)
```

which yields for example:

> ([1.0, 1.2, 3.2, 1.1, 1.2],)

The output is a tuple where each tuple element corresponds to the respective output values of the `statistic` function. In this case, since `median` only returns a single value per resampling, the first tuple element contains all the medians estimated from each resampling.

**Comment by Boxylmer** [comment]
Thanks! I missed it completely. Now I can just plot a histogram of `straps(bs)` and hopefully I'll see something bell shaped :)

**Comment by skleinbo** [comment]
Can `straps` be regarded as API? If yes, it should be documented.

**Comment by Boxylmer** [comment]
(I'm all for this as well!)
